// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	abstraction "gitlab.com/stoqu/stoqu-be/internal/model/abstraction"

	dto "gitlab.com/stoqu/stoqu-be/internal/model/dto"

	mock "github.com/stretchr/testify/mock"
)

// Brand is an autogenerated mock type for the Brand type
type Brand struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, payload
func (_m *Brand) Create(ctx context.Context, payload dto.CreateBrandRequest) (dto.BrandResponse, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.BrandResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateBrandRequest) dto.BrandResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.BrandResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateBrandRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, payload
func (_m *Brand) Delete(ctx context.Context, payload dto.ByIDRequest) (dto.BrandResponse, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.BrandResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.ByIDRequest) dto.BrandResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.BrandResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.ByIDRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Find provides a mock function with given fields: ctx, filterParam
func (_m *Brand) Find(ctx context.Context, filterParam abstraction.Filter) ([]dto.BrandResponse, abstraction.PaginationInfo, error) {
	ret := _m.Called(ctx, filterParam)

	var r0 []dto.BrandResponse
	if rf, ok := ret.Get(0).(func(context.Context, abstraction.Filter) []dto.BrandResponse); ok {
		r0 = rf(ctx, filterParam)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.BrandResponse)
		}
	}

	var r1 abstraction.PaginationInfo
	if rf, ok := ret.Get(1).(func(context.Context, abstraction.Filter) abstraction.PaginationInfo); ok {
		r1 = rf(ctx, filterParam)
	} else {
		r1 = ret.Get(1).(abstraction.PaginationInfo)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, abstraction.Filter) error); ok {
		r2 = rf(ctx, filterParam)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: ctx, payload
func (_m *Brand) FindByID(ctx context.Context, payload dto.ByIDRequest) (dto.BrandResponse, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.BrandResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.ByIDRequest) dto.BrandResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.BrandResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.ByIDRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, payload
func (_m *Brand) Update(ctx context.Context, payload dto.UpdateBrandRequest) (dto.BrandResponse, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.BrandResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdateBrandRequest) dto.BrandResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.BrandResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.UpdateBrandRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewBrand interface {
	mock.TestingT
	Cleanup(func())
}

// NewBrand creates a new instance of Brand. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBrand(t mockConstructorTestingTNewBrand) *Brand {
	mock := &Brand{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
