// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	abstraction "gitlab.com/stoqu/stoqu-be/internal/model/abstraction"

	dto "gitlab.com/stoqu/stoqu-be/internal/model/dto"

	mock "github.com/stretchr/testify/mock"
)

// Packet is an autogenerated mock type for the Packet type
type Packet struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, payload
func (_m *Packet) Create(ctx context.Context, payload dto.CreatePacketRequest) (dto.PacketResponse, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.PacketResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreatePacketRequest) dto.PacketResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.PacketResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.CreatePacketRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, payload
func (_m *Packet) Delete(ctx context.Context, payload dto.ByIDRequest) (dto.PacketResponse, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.PacketResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.ByIDRequest) dto.PacketResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.PacketResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.ByIDRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Find provides a mock function with given fields: ctx, filterParam
func (_m *Packet) Find(ctx context.Context, filterParam abstraction.Filter) ([]dto.PacketResponse, abstraction.PaginationInfo, error) {
	ret := _m.Called(ctx, filterParam)

	var r0 []dto.PacketResponse
	if rf, ok := ret.Get(0).(func(context.Context, abstraction.Filter) []dto.PacketResponse); ok {
		r0 = rf(ctx, filterParam)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.PacketResponse)
		}
	}

	var r1 abstraction.PaginationInfo
	if rf, ok := ret.Get(1).(func(context.Context, abstraction.Filter) abstraction.PaginationInfo); ok {
		r1 = rf(ctx, filterParam)
	} else {
		r1 = ret.Get(1).(abstraction.PaginationInfo)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, abstraction.Filter) error); ok {
		r2 = rf(ctx, filterParam)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: ctx, payload
func (_m *Packet) FindByID(ctx context.Context, payload dto.ByIDRequest) (dto.PacketResponse, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.PacketResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.ByIDRequest) dto.PacketResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.PacketResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.ByIDRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, payload
func (_m *Packet) Update(ctx context.Context, payload dto.UpdatePacketRequest) (dto.PacketResponse, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.PacketResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdatePacketRequest) dto.PacketResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.PacketResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.UpdatePacketRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPacket interface {
	mock.TestingT
	Cleanup(func())
}

// NewPacket creates a new instance of Packet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPacket(t mockConstructorTestingTNewPacket) *Packet {
	mock := &Packet{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
