// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	abstraction "gitlab.com/stoqu/stoqu-be/internal/model/abstraction"

	dto "gitlab.com/stoqu/stoqu-be/internal/model/dto"

	mock "github.com/stretchr/testify/mock"
)

// Product is an autogenerated mock type for the Product type
type Product struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, payload
func (_m *Product) Create(ctx context.Context, payload dto.CreateProductRequest) (dto.ProductResponse, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.ProductResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateProductRequest) dto.ProductResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.ProductResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateProductRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, payload
func (_m *Product) Delete(ctx context.Context, payload dto.ByIDRequest) (dto.ProductResponse, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.ProductResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.ByIDRequest) dto.ProductResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.ProductResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.ByIDRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Find provides a mock function with given fields: ctx, filterParam
func (_m *Product) Find(ctx context.Context, filterParam abstraction.Filter) ([]dto.ProductViewResponse, abstraction.PaginationInfo, error) {
	ret := _m.Called(ctx, filterParam)

	var r0 []dto.ProductViewResponse
	if rf, ok := ret.Get(0).(func(context.Context, abstraction.Filter) []dto.ProductViewResponse); ok {
		r0 = rf(ctx, filterParam)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ProductViewResponse)
		}
	}

	var r1 abstraction.PaginationInfo
	if rf, ok := ret.Get(1).(func(context.Context, abstraction.Filter) abstraction.PaginationInfo); ok {
		r1 = rf(ctx, filterParam)
	} else {
		r1 = ret.Get(1).(abstraction.PaginationInfo)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, abstraction.Filter) error); ok {
		r2 = rf(ctx, filterParam)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: ctx, payload
func (_m *Product) FindByID(ctx context.Context, payload dto.ByIDRequest) (dto.ProductResponse, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.ProductResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.ByIDRequest) dto.ProductResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.ProductResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.ByIDRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, payload
func (_m *Product) Update(ctx context.Context, payload dto.UpdateProductRequest) (dto.ProductResponse, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.ProductResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdateProductRequest) dto.ProductResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.ProductResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.UpdateProductRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewProduct interface {
	mock.TestingT
	Cleanup(func())
}

// NewProduct creates a new instance of Product. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProduct(t mockConstructorTestingTNewProduct) *Product {
	mock := &Product{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
