// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	abstraction "gitlab.com/stoqu/stoqu-be/internal/model/abstraction"

	dto "gitlab.com/stoqu/stoqu-be/internal/model/dto"

	mock "github.com/stretchr/testify/mock"
)

// ReminderStock is an autogenerated mock type for the ReminderStock type
type ReminderStock struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, payload
func (_m *ReminderStock) Create(ctx context.Context, payload dto.CreateReminderStockRequest) (dto.ReminderStockResponse, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.ReminderStockResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateReminderStockRequest) dto.ReminderStockResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.ReminderStockResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateReminderStockRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, payload
func (_m *ReminderStock) Delete(ctx context.Context, payload dto.ByIDRequest) (dto.ReminderStockResponse, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.ReminderStockResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.ByIDRequest) dto.ReminderStockResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.ReminderStockResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.ByIDRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Find provides a mock function with given fields: ctx, filterParam
func (_m *ReminderStock) Find(ctx context.Context, filterParam abstraction.Filter) ([]dto.ReminderStockResponse, abstraction.PaginationInfo, error) {
	ret := _m.Called(ctx, filterParam)

	var r0 []dto.ReminderStockResponse
	if rf, ok := ret.Get(0).(func(context.Context, abstraction.Filter) []dto.ReminderStockResponse); ok {
		r0 = rf(ctx, filterParam)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ReminderStockResponse)
		}
	}

	var r1 abstraction.PaginationInfo
	if rf, ok := ret.Get(1).(func(context.Context, abstraction.Filter) abstraction.PaginationInfo); ok {
		r1 = rf(ctx, filterParam)
	} else {
		r1 = ret.Get(1).(abstraction.PaginationInfo)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, abstraction.Filter) error); ok {
		r2 = rf(ctx, filterParam)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: ctx, payload
func (_m *ReminderStock) FindByID(ctx context.Context, payload dto.ByIDRequest) (dto.ReminderStockResponse, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.ReminderStockResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.ByIDRequest) dto.ReminderStockResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.ReminderStockResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.ByIDRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, payload
func (_m *ReminderStock) Update(ctx context.Context, payload dto.UpdateReminderStockRequest) (dto.ReminderStockResponse, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.ReminderStockResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdateReminderStockRequest) dto.ReminderStockResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.ReminderStockResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.UpdateReminderStockRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewReminderStock interface {
	mock.TestingT
	Cleanup(func())
}

// NewReminderStock creates a new instance of ReminderStock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewReminderStock(t mockConstructorTestingTNewReminderStock) *ReminderStock {
	mock := &ReminderStock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
