// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	abstraction "gitlab.com/stoqu/stoqu-be/internal/model/abstraction"

	dto "gitlab.com/stoqu/stoqu-be/internal/model/dto"

	mock "github.com/stretchr/testify/mock"
)

// Role is an autogenerated mock type for the Role type
type Role struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, payload
func (_m *Role) Create(ctx context.Context, payload dto.CreateRoleRequest) (dto.RoleResponse, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.RoleResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateRoleRequest) dto.RoleResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.RoleResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateRoleRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, payload
func (_m *Role) Delete(ctx context.Context, payload dto.ByIDRequest) (dto.RoleResponse, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.RoleResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.ByIDRequest) dto.RoleResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.RoleResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.ByIDRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Find provides a mock function with given fields: ctx, filterParam
func (_m *Role) Find(ctx context.Context, filterParam abstraction.Filter) ([]dto.RoleResponse, abstraction.PaginationInfo, error) {
	ret := _m.Called(ctx, filterParam)

	var r0 []dto.RoleResponse
	if rf, ok := ret.Get(0).(func(context.Context, abstraction.Filter) []dto.RoleResponse); ok {
		r0 = rf(ctx, filterParam)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.RoleResponse)
		}
	}

	var r1 abstraction.PaginationInfo
	if rf, ok := ret.Get(1).(func(context.Context, abstraction.Filter) abstraction.PaginationInfo); ok {
		r1 = rf(ctx, filterParam)
	} else {
		r1 = ret.Get(1).(abstraction.PaginationInfo)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, abstraction.Filter) error); ok {
		r2 = rf(ctx, filterParam)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: ctx, payload
func (_m *Role) FindByID(ctx context.Context, payload dto.ByIDRequest) (dto.RoleResponse, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.RoleResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.ByIDRequest) dto.RoleResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.RoleResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.ByIDRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, payload
func (_m *Role) Update(ctx context.Context, payload dto.UpdateRoleRequest) (dto.RoleResponse, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.RoleResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdateRoleRequest) dto.RoleResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.RoleResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.UpdateRoleRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRole interface {
	mock.TestingT
	Cleanup(func())
}

// NewRole creates a new instance of Role. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRole(t mockConstructorTestingTNewRole) *Role {
	mock := &Role{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
