// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	abstraction "gitlab.com/stoqu/stoqu-be/internal/model/abstraction"

	dto "gitlab.com/stoqu/stoqu-be/internal/model/dto"

	mock "github.com/stretchr/testify/mock"
)

// Stock is an autogenerated mock type for the Stock type
type Stock struct {
	mock.Mock
}

// Convertion provides a mock function with given fields: ctx, payload
func (_m *Stock) Convertion(ctx context.Context, payload dto.ConvertionStockRequest) (dto.StockConvertionResponse, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.StockConvertionResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.ConvertionStockRequest) dto.StockConvertionResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.StockConvertionResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.ConvertionStockRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Find provides a mock function with given fields: ctx, filterParam
func (_m *Stock) Find(ctx context.Context, filterParam abstraction.Filter) ([]dto.StockViewResponse, abstraction.PaginationInfo, error) {
	ret := _m.Called(ctx, filterParam)

	var r0 []dto.StockViewResponse
	if rf, ok := ret.Get(0).(func(context.Context, abstraction.Filter) []dto.StockViewResponse); ok {
		r0 = rf(ctx, filterParam)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.StockViewResponse)
		}
	}

	var r1 abstraction.PaginationInfo
	if rf, ok := ret.Get(1).(func(context.Context, abstraction.Filter) abstraction.PaginationInfo); ok {
		r1 = rf(ctx, filterParam)
	} else {
		r1 = ret.Get(1).(abstraction.PaginationInfo)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, abstraction.Filter) error); ok {
		r2 = rf(ctx, filterParam)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: ctx, payload
func (_m *Stock) FindByID(ctx context.Context, payload dto.ByIDRequest) (dto.StockResponse, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.StockResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.ByIDRequest) dto.StockResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.StockResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.ByIDRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// History provides a mock function with given fields: ctx, filterParam
func (_m *Stock) History(ctx context.Context, filterParam abstraction.Filter) ([]dto.StockHistoryResponse, abstraction.PaginationInfo, error) {
	ret := _m.Called(ctx, filterParam)

	var r0 []dto.StockHistoryResponse
	if rf, ok := ret.Get(0).(func(context.Context, abstraction.Filter) []dto.StockHistoryResponse); ok {
		r0 = rf(ctx, filterParam)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.StockHistoryResponse)
		}
	}

	var r1 abstraction.PaginationInfo
	if rf, ok := ret.Get(1).(func(context.Context, abstraction.Filter) abstraction.PaginationInfo); ok {
		r1 = rf(ctx, filterParam)
	} else {
		r1 = ret.Get(1).(abstraction.PaginationInfo)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, abstraction.Filter) error); ok {
		r2 = rf(ctx, filterParam)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Movement provides a mock function with given fields: ctx, payload
func (_m *Stock) Movement(ctx context.Context, payload dto.MovementStockRequest) (dto.StockMovementResponse, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.StockMovementResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.MovementStockRequest) dto.StockMovementResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.StockMovementResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.MovementStockRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Transaction provides a mock function with given fields: ctx, payload
func (_m *Stock) Transaction(ctx context.Context, payload dto.TransactionStockRequest) (dto.StockTransactionResponse, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.StockTransactionResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.TransactionStockRequest) dto.StockTransactionResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.StockTransactionResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.TransactionStockRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionProcess provides a mock function with given fields: ctx, payload
func (_m *Stock) TransactionProcess(ctx context.Context, payload dto.TransactionStockRequest) (dto.StockTransactionResponse, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.StockTransactionResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.TransactionStockRequest) dto.StockTransactionResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.StockTransactionResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.TransactionStockRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewStock interface {
	mock.TestingT
	Cleanup(func())
}

// NewStock creates a new instance of Stock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStock(t mockConstructorTestingTNewStock) *Stock {
	mock := &Stock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
